//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RationalVote
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RationalVoteContainer : DbContext
    {
        public RationalVoteContainer()
            : base("name=RationalVoteContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<EmailVerificationToken> EmailVerificationTokens { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Debate> Debates { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<DebateTag> DebateTags { get; set; }
        public virtual DbSet<DebateLink> DebateLinks { get; set; }
        public virtual DbSet<DebateLinkVote> DebateLinkVotes { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
    }
}
